spring:
  application:
    name: MySpringBoot2Dbase
  datasource:
    url: jdbc:h2:C:\Users\obita\IdeaProjects\programming_25-26\Lr6\MySpringBoot2Dbase\MySpringBoot2Dbase\testbd\students
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console.enabled: true
server:
  port: 8082